--- 
## This is a copy of nginx-task.yml. 
## The new setup.yml is created to conforms writing playbook guidelines.
 
## these are nginx inclue task
- name: install python-software-properties
  action: apt name='python-software-properties' state=installed

- name: "add nginx ppa if it ubuntu 10.04 and up"
  action: apt_repository repo=ppa:nginx/stable
  only_if: "$is_ubuntu and $is_10_up"

- name: update apt repo
  action: apt update-cache=yes

- name: install nginx 
  action: apt name=nginx state=installed

- name:  copy fixed init for nginx
  action: copy src=nginx/files/nginx.init dest=/etc/init.d/nginx mode=0755  backup=yes

- name: service nginx 
  action: service name=nginx state=started 

- name: write nginx.conf 
  action: template src='nginx/templates/nginx.conf.j2' dest='/etc/nginx/nginx.conf' backup=yes
  notify:
    - restart nginx
